apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  annotation: 
    specific: "{{ .Values.perEnvironmentConfiguration }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.image }}
          ports:
            - containerPort: {{ .Values.port }}
