apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: production-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pablorhuam/gitops_configuration.git
    targetRevision: HEAD
    # path: base
    helm:
      valueFiles:
        - environments/production/values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
