apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/pablorhuam/gitops_configuration.git
    targetRevision: HEAD
    path: base
    helm:
      valueFiles:
        - ../common/values.yaml
        - ../variants/staging/values.yaml
        - ../environments/staging/image.yaml
        - ../environments/staging/replicas.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging-namespace
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

